services:
  - type: web
    name: movielinkbd-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: PORT
        value: 10000
