name = "movielinkbd-video-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Worker configuration
[env.production]
name = "movielinkbd-video-proxy"

# Limits and timeouts
[limits]
cpu_ms = 50000  # 50 seconds CPU time limit

# KV storage (optional, for caching if needed)
# [[kv_namespaces]]
# binding = "VIDEO_CACHE"
# id = "your-kv-namespace-id"

# Environment variables (if needed)
# [vars]
# ALLOWED_DOMAINS = "play.movielinkbd.mom,playk8.movielinkbd.sbs,moviexp.movielinkbd.sbs,movielinkbd.shop,movielinkbd.one"
